apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: psxqrzzyt-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:681e0a78cbfa228a6344dbd15a3f08c7a518e5cf@sha256:405bc91d6ace8aba92db2edec7685874e4a25812d0fd008c130c39aa1a2ec2cb
          name: container-image
